### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Caerind** [Cmdu76/Delmia#3]
We need to separate the project on few different parts.

1) NodeEngine
2) GameCore
3) MainServer
4) GameServer
5) Client

At the moment, we should focus on the first two items to have a stable base to start with.

**Comment by Caerind** [comment]
NodeEngine is already separated on submodules. 
- The Application module is fine (but can still be improved). 
- The Utils module will be improved when needed.
- The SimpleGui part needs LineEdit and Slider to be really usable.
- Then the Core part needs a lot of work. We need to add components (Physics, Particles...). But I also think that some problems remains on this part. I'm actually thinking about transformations and bounds (Need to test it). We also need to have a better access to Entities contained in the World, and maybe an improved ID system. We should also try to think on Networking. And maybe find a way to simplify the NWorld as possible.

**Comment by Cmdu76** [comment]
2) GameCore contains stuff like : Isometric maths and our entities types.
This is also our game logic, actions, properties... This is like a cheated game to test features for the client.

**Comment by Cmdu76** [comment]
3 and 4 have a lot in common since they will use a common base.
We need to have a good implementation of few things : 
- Improved commands
- Improved messages (and private messages)
- User permissions: Admin/(Moderator)/User
- Kick/Ban/BanIP
- Better user management

3) MainServer
- Database
- Secured passwords
- Host GameServers
- Chat Rooms

4) GameServer
- Game -> Mean a lot of things that we will think and implement in the GameCore part

**Comment by Cmdu76** [comment]
5) Client
- MainServer connection/disconnection
- GameServer connection/disconnection
- Client part of the game

**Comment by ghost** [comment]
TODO GameCore part of the game :
- Building's interaction
- Moving unit, path finding: select unit, path smoothing, unit interact with Building
- Map generation

**Comment by Caerind** [comment]
All "tasks" can be found on Trello with this link : https://trello.com/b/DFSmrCfx/delmia
